ALTER TABLE EXPLICACION ADD COLUMN tipo numeric(1,0);
UPDATE EXPLICACION SET tipo = 0;
ALTER TABLE explicacion ALTER COLUMN tipo SET NOT NULL;

ALTER TABLE EXPLICACION ADD COLUMN fecha_compromiso timestamp without time zone;
ALTER TABLE EXPLICACION ADD COLUMN fecha_real timestamp without time zone;

ALTER TABLE CLASE_PROBLEMA ADD COLUMN tipo numeric(1,0);
UPDATE CLASE_PROBLEMA SET tipo = 0;
ALTER TABLE CLASE_PROBLEMA ALTER COLUMN tipo SET NOT NULL;
