CREATE OR REPLACE FUNCTION checkSql() RETURNS VOID AS
$BODY$
BEGIN
	IF EXISTS (SELECT * FROM information_schema.table_constraints WHERE table_name = 'INDICADOR_POR_PERSPECTIVA' AND constraint_name = 'FK_INDICADOR_PERSPECTIVA')
	THEN
		execute 'ALTER TABLE INDICADOR_POR_PERSPECTIVA DROP CONSTRAINT FK_INDICADOR_PERSPECTIVA';
	END IF;
END;
$BODY$
LANGUAGE 'plpgsql';
SELECT checkSql();
DROP FUNCTION checkSql();
