DECLARE
	vCount NUMBER(2);

BEGIN
	SELECT COUNT(*) INTO vCount FROM USER_TAB_COLUMNS WHERE COLUMN_NAME = 'INICIATIVA_ASOCIADA_ID' AND TABLE_NAME = 'INICIATIVA';
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX IE_INICIATIVA_ASOCIADO';
		execute immediate 'ALTER TABLE INICIATIVA DROP CONSTRAINT fk_iniciativa_asociadaid';
		execute immediate 'ALTER TABLE INICIATIVA DROP COLUMN INICIATIVA_ASOCIADA_ID';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM USER_TAB_COLUMNS WHERE COLUMN_NAME = 'INICIATIVA_ASOCIADA_PLAN_ID' AND TABLE_NAME = 'INICIATIVA';
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX IE_INICIATIVA_ASOCIADO_PLAN';
		execute immediate 'ALTER TABLE INICIATIVA DROP CONSTRAINT fk_iniciativa_asociada_plan';
		execute immediate 'ALTER TABLE INICIATIVA DROP COLUMN INICIATIVA_ASOCIADA_PLAN_ID';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM USER_TAB_COLUMNS WHERE COLUMN_NAME = 'INICIATIVA_ASOCIADA_PLAN_ID' AND TABLE_NAME = 'PRY_ACTIVIDAD';
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE pry_actividad DROP COLUMN iniciativa_asociada_plan_id';
	END;
	END IF;
	
END;
/

UPDATE afw_sistema SET build = '141114';

COMMIT;
