DECLARE
	vCount NUMBER(2);

BEGIN
	SELECT COUNT(*) INTO vCount FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER('FK_INDICADOR_PERSPECTIVA') AND TABLE_NAME = UPPER('INDICADOR_POR_PERSPECTIVA');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE INDICADOR_POR_PERSPECTIVA DROP CONSTRAINT FK_INDICADOR_PERSPECTIVA';
	END;
	END IF;
END;
/

COMMIT;
