DECLARE
	vCount NUMBER(5);

BEGIN
	SELECT COUNT(*) INTO vCount FROM ALL_CONSTRAINTS WHERE TABLE_NAME = UPPER('FORMULA') AND CONSTRAINT_NAME = UPPER('pk_formula');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE FORMULA DROP CONSTRAINT pk_formula';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('pk_formula');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX pk_formula';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('xif1formula');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX xif1formula';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('xif2formula');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX xif2formula';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('xif3formula');
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DROP INDEX xif3formula';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM INDICADOR WHERE CLASE_ID NOT IN (SELECT CLASE_ID FROM CLASE);
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DELETE FROM INDICADOR WHERE CLASE_ID NOT IN (SELECT CLASE_ID FROM CLASE)';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM CONJUNTO_FORMULA WHERE INDICADOR_ID NOT IN (SELECT INDICADOR_ID FROM INDICADOR);
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DELETE FROM CONJUNTO_FORMULA WHERE INDICADOR_ID NOT IN (SELECT INDICADOR_ID FROM INDICADOR)';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM FORMULA WHERE INDICADOR_ID NOT IN (SELECT INDICADOR_ID FROM INDICADOR);
	IF vCount > 0 THEN 
	BEGIN
		execute immediate 'DELETE FROM FORMULA WHERE INDICADOR_ID NOT IN (SELECT INDICADOR_ID FROM INDICADOR)';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('ak_formula');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'CREATE UNIQUE INDEX ak_formula ON formula (indicador_id ASC,serie_id ASC)';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM ALL_CONSTRAINTS WHERE TABLE_NAME = UPPER('FORMULA') AND CONSTRAINT_NAME = UPPER('pk_formula');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE FORMULA ADD CONSTRAINT pk_formula PRIMARY KEY (indicador_id, serie_id)';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('ie_formula_indicadorid');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'CREATE  INDEX ie_formula_indicadorid ON FORMULA (indicador_id   ASC)';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM ALL_IND_COLUMNS WHERE TABLE_NAME = UPPER('FORMULA') AND INDEX_NAME = UPPER('ie_formula_serie');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'CREATE  INDEX ie_formula_serie ON FORMULA (serie_id   ASC)';
	END;
	END IF;

	SELECT COUNT(*) INTO vCount FROM ALL_CONSTRAINTS WHERE TABLE_NAME = UPPER('FORMULA') AND CONSTRAINT_NAME = UPPER('fk_formula_serie');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE FORMULA ADD (CONSTRAINT fk_formula_serie FOREIGN KEY (serie_id) REFERENCES serie_tiempo (serie_id) ON DELETE CASCADE)';
	END;
	END IF;
	
	SELECT COUNT(*) INTO vCount FROM ALL_CONSTRAINTS WHERE TABLE_NAME = UPPER('FORMULA') AND CONSTRAINT_NAME = UPPER('fk_formula_indicador');
	IF vCount = 0 THEN 
	BEGIN
		execute immediate 'ALTER TABLE FORMULA ADD (CONSTRAINT FK_FORMULA_INDICADOR FOREIGN KEY (INDICADOR_ID) REFERENCES INDICADOR (INDICADOR_ID) ON DELETE CASCADE)';
	END;
	END IF;
	
END;
/

COMMIT;
